In [1]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"GPU detected: {torch.cuda.get_device_name(0)}")

PyTorch version: 2.6.0+cu124
CUDA available: True
GPU detected: NVIDIA GeForce RTX 3050 6GB Laptop GPU


In [2]:
X = torch.tensor([[1.0, 4.0, 7.0], [2.0, 3.0, 6.0]])
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [3]:
X.shape

torch.Size([2, 3])

In [5]:
X.dtype

torch.float32

In [6]:
X[0, 1]

tensor(4.)

In [7]:
X[1, 2]

tensor(6.)

In [8]:
X[:, 1]

tensor([4., 3.])

In [10]:
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [9]:
10 * (X + 1.0)  # itemwise addition and multiplication

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [11]:
X.exp()  # itemwise exponential

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [12]:
X.mean()

tensor(3.8333)

In [13]:
X.max(dim=0)

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [14]:
X @ X.T  # matrix transpose and matrix multiplication

tensor([[66., 56.],
        [56., 49.]])

In [15]:
import numpy as np
X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [16]:
torch.tensor(np.array([[1., 2., 7.], [2., 3., 6.]]))

tensor([[1., 2., 7.],
        [2., 3., 6.]], dtype=torch.float64)

In [ ]:
torch.FloatTensor(np.array([[1., 4., 7.], [2., 3., 6]])) #converts to 32 bits as it is preferred for faster computation

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [18]:
X[:, 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [20]:
X.relu_()
X

tensor([[1., 0., 7.],
        [2., 0., 6.]])

In [24]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"
device

'cuda'

In [25]:
M = torch.tensor([[1., 2., 3.,], [4., 5., 6.]])
M = M.to(device)

In [26]:
M.device

device(type='cuda', index=0)

In [27]:
M = torch.tensor([[1., 2., 3.], [4., 5., 6.]], device=device)

In [28]:
R = M @ M.T
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')

In [29]:
M = torch.rand((1000, 1000)) #on the cpu
%timeit M @ M.T

3.51 ms ± 47.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [32]:
M = torch.rand((1000, 1000), device="cuda")  # on the GPU
%timeit M @ M.T

476 μs ± 7.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


 For example,consider a simple function, f(x) = x2. Differential calculus tells us that the derivative of this function is f’(x) = 2x. If we evaluate f(5) and f'(5), we get 25 and 10, respectively. Let’s see if PyTorch agrees:   [pg no 323, 324]

In [35]:
x = torch.tensor(5.0, requires_grad=True)
f = x ** 2
f

tensor(25., grad_fn=<PowBackward0>)

In [36]:
f.backward()
x.grad

tensor(10.)

In [37]:
learning_rate = 0.1
with torch.no_grad():
    x -= learning_rate * x.grad  #gradient descent step

In [38]:
x_detached = x.detach()
x_detached -= learning_rate * x.grad

In [39]:
x.grad.zero_()

tensor(0.)

In [40]:
learning_rate = 0.1
x = torch.tensor(5.0, requires_grad=True)
for iteration in range(100):
    f = x ** 2  # forward pass
    f.backward()  # backward pass
    with torch.no_grad():
        x -= learning_rate * x.grad  # gradient descent step
        x.grad.zero_()  # reset the gradients

In [ ]:
# t = torch.tensor(2.0, requires_grad=True)
# z = t.exp()  # this is an intermediate result
# z += 1  # this is an in-place operation
# z.backward()  #  RuntimeError!

In [ ]:
# pg 326

### https://0byte.io/articles/pytorch_introduction.html